website/views.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from .models import Expense
from . import db
from datetime import datetime
from flask_login import login_required, current_user

views = Blueprint('views', __name__)

# Rota para a página inicial
@views.route('/', methods=['GET'])
@login_required
def home():
    try:
        expenses = Expense.query.filter_by(user_id=current_user.id)
        total_value = sum(expense.value for expense in expenses)
        return render_template('home.html', user=current_user, total_value=total_value)
    except Exception as e:
        flash('Ocorreu um erro ao carregar as despesas.', category='error')
        return redirect(url_for('views.home'))

# Rota para adicionar uma nova despesa
@views.route('/despesas', methods=['GET', 'POST'])
@login_required
def expense():
    if request.method == 'POST':
        try:
            name = request.form.get('name')
            value_str = request.form.get('value')
            value_str = value_str.replace('R$', '').replace('.', '').replace(',', '.').strip()
            value = float(value_str) if value_str else 0.0
            is_installment = bool(request.form.get('is_installment'))
            installment_count = int(request.form.get('installment_count'))
            date = request.form.get('date')
            due_date = '0/0/0000'
            comment = request.form.get('comment')
            default_cat = request.form.get('category')

            # Mapear a categoria padrão
            match default_cat:
                case '1':
                    default_cat = 'Alimentação'
                case '2':
                    default_cat = 'Transporte'
                case '3':
                    default_cat = 'Moradia'
                case '4':
                    default_cat = 'Lazer'
                case '5':
                    default_cat = 'Educação'

            if is_installment:
                installment_value_str = request.form.get('installment_value')
                installment_value_str = installment_value_str.replace('R$', '').replace('.', '').replace(',', '.').strip()
                installment_value = float(installment_value_str)
                due_date = request.form.get('due_date')

                value = installment_value * installment_count  # Somar valor total das parcelas
                date = datetime.now().date()

            # Cria uma instância de Expense
            expense = Expense(
                name=name,
                value=value,
                is_installment=is_installment,
                installment_count=installment_count,
                installment_value=value / installment_count,
                due_date=due_date,
                user_id=current_user.id,
                date=date,
                comment=comment,
                default_cat=default_cat
            )

            # Salve a despesa no banco de dados
            db.session.add(expense)
            db.session.commit()

            flash('Despesa adicionada', category='success')
        except Exception as e:
            flash(f'Ocorreu um erro ao atualizar a despesa. {e}', category='error')
            db.session.rollback()

    return render_template('expense.html', user=current_user)

# Rota para editar uma despesa existente
@views.route('/edit/<int:expense_id>', methods=['GET', 'POST'])
@login_required
def edit_expense(expense_id):
    expense = Expense.query.get_or_404(expense_id)

    if request.method == 'POST':
        try:
            # Obtenha os dados enviados no formulário de edição
            name = request.form['name']
            value_str = request.form.get('value')
            value_str = value_str.replace('R$', '').replace('.', '').replace(',', '.').strip()
            value = float(value_str) if value_str else 0.0
            is_installment = bool(request.form.get('is_installment'))
            installment_value = float(request.form.get('installment_value')) if is_installment else None
            installment_count = int(request.form.get('installment_count')) if is_installment else None
            due_date = request.form.get('due_date') if is_installment else None
            comment = request.form.get('comment')
            default_cat = request.form.get('category')

            # Mapear a categoria padrão
            match default_cat:
                case '1':
                    default_cat = 'Alimentação'
                case '2':
                    default_cat = 'Transporte'
                case '3':
                    default_cat = 'Moradia'
                case '4':
                    default_cat = 'Lazer'
                case '5':
                    default_cat = 'Educação'

            # Atualize os campos da despesa existente
            expense.name = name
            expense.value = value
            expense.is_installment = is_installment
            expense.installment_value = installment_value
            expense.installment_count = installment_count
            expense.due_date = due_date
            expense.comment = comment
            expense.default_cat = default_cat
            # Outros campos de atualização

            # Salve as alterações no banco de dados
            db.session.commit()

            flash('Despesa atualizada', category='success')
            return redirect(url_for('views.home'))
        except Exception as e:
            flash(f'Ocorreu um erro ao atualizar a despesa. {e}', category='error')
            db.session.rollback()

    return render_template('edit_expense.html', expense=expense, user=current_user)

@views.route('/delete/<int:expense_id>', methods=['GET'])
@login_required
def delete_expense(expense_id):
    try:
        expense = Expense.query.get_or_404(expense_id)
        db.session.delete(expense)
        db.session.commit()
        flash(f'Despesa {expense.name} excluída.', category='success')
    except Exception as e:
        flash('Ocorreu um erro ao tentar excluir.', category='error')
        db.session.rollback()

    return redirect(url_for('views.home'))

website/templates/base.html
<!DOCTYPE html>
<html lang="pt-BR" data-bs-theme="dark">
<head>
    <meta charset="UTF-3">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
            integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
            crossorigin="anonymous"
    />
    <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
            crossorigin="anonymous"
    />
    <link rel="icon" href="../static/images/rocket-icon.svg" type="image/png">

    {% block head %}
    {% endblock %}
    <title>{% block title %} Home {% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
            {% if user.is_authenticated %}
            <a class="nav-item nav-link" id="home" href="/">Página Inicial</a>
            <a class="nav-item nav-link" id="expense" href="/despesas">Adicionar gastos</a>
            <a class="nav-item nav-link" id="logout" href="/auth/logout">Logout</a>
            {% else %}
            <a class="nav-item nav-link" id="login" href="/auth/login">Login</a>
            <a class="nav-item nav-link" id="sign-up" href="/auth/sign-up">Registrar</a>
            {% endif %}
        </div>
      </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% elif category == 'success' %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
    </button>
    </div>
    {% else %}
    <div class="alert alert-primary" role="alert">
    {{ message }}
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}
    <div class="container">
    <div>
        {% block content %}

        {% endblock %}
    </div>
    </div>
    <script
        src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"
    ></script>
    <script
        src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"
    ></script>
    <script
        src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"
    ></script>
    {% block script %}
    {% endblock %}
</body>
</html>

website/templates/edit_expense.html
{% extends "base.html" %}
{% block title %} Página Inicial {% endblock %}

{% block head %}

{% endblock %}

{% block content %}
<h1>Editar Despesa</h1>
<form method="POST" action="{{ url_for('views.edit_expense', expense_id=expense.id) }}">
    <div class="form-group">
        <label for="name">Nome:</label>
        <input type="text" class="form-control" id="name" name="name" value="{{ expense.name }}" required>
    </div>

    <div class="form-group">
            <div class="form-check">
                <input type="checkbox" id="is_installment" name="is_installment" class="form-check-input" {% if expense.is_installment == 1 %} checked {% endif %}>
                <label for="is_installment" class="form-check-label">Parcelado</label>
            </div>
        </div>

        <div id="installment-fields" {% if expense.is_installment == 0 %} style="display: none;" {% endif %}>
            <!-- Campos para despesas parceladas -->
            <div class="form-group">
                <label for="installment_value">Valor da Parcela:</label>
                <input type="text" id="installment_value" name="installment_value"
                       oninput="formatarMoeda('installment_value')" value="{{ expense.installment_value }}" class="form-control" step="0.01">
            </div>
            <div class="form-group">
                <label for="installment_count">Número de Parcelas:</label>
                <input type="number" id="installment_count" name="installment_count" class="form-control" value="{{ expense.installment_count }}">
            </div>
            <div class="form-group">
                <label>Valor Restante:</label>
                <span id="valor_restante"></span>
            </div>
            <div class="form-group">
                <label for="due_date">Inicio da parcela:</label>
                <input type="date" id="due_date" name="due_date" value="{{ expense.due_date }}" class="form-control">
            </div>
            <div class="form-group">
                <label>Informações das Parcelas:</label>
                <div id="parcelas-list">
                    <!-- Os três primeiros itens da lista de parcelas são exibidos aqui -->
                </div>
                <div id="show-all-installments" style="display: none;">
                    <!-- Os demais itens da lista de parcelas são exibidos aqui quando o usuário clica em "Ver todas as parcelas" -->
                </div>
                <span id="show-installments-span" class="link-span" style="display: none;">Ver todas as parcelas</span>
            </div>
        </div>
        <label for="value">Valor total:</label>
            <input type="text" id="value" name="value" oninput="formatarMoeda('value')" placeholder="Insira o valor"
                   class="form-control" value="{{ expense.value }}" {% if expense.is_installment == 1 %} aria-disabled="true" {% endif %}>

        <div class="form-group" id="date-field">
            <label for="date">Data:</label>
            <input type="date" id="date" name="date" class="form-control" value="{{ expense.date }}">
        </div>

        <div class="form-group">
            <label for="category">Categoria:</label>
            <select id="category" name="category" class="form-control">
                <option value="" selected disabled>Selecione uma categoria</option>
                <option value="1">Alimentação</option>
                <option value="2">Transporte</option>
                <option value="3">Moradia</option>
                <option value="4">Lazer</option>
                <option value="5">Educação</option>
                {% for category in user.categories %}
                <option value="{{ category.id }}">{{ category.name }}</option>
                {% endfor %}
            </select>
        </div>

        <div class="form-group">
            <label for="comment">Observação:</label>
            <textarea id="comment" name="comment" class="form-control" maxlength="500">{{ expense.comment }}</textarea>
        </div>

    <button type="submit" class="btn btn-primary">Salvar</button>

</form>

{% endblock %}

{% block script %}
<script src="{{ url_for('static', filename='expense.js') }}"></script>
{% endblock %}

website/templates/expense.html
{% extends "base.html" %}
{% block head %}
<style>
    .link-span {
        color: blue;
        text-decoration: underline;
        cursor: pointer;
    }

    .link-span:hover {
        text-decoration: none;
    }
</style>
{% endblock %}

{% block title %} Adicionar nova despesa {% endblock %}

{% block content %}
<div class="container">
    <h1>Criar Despesa</h1>
    <form method="POST">
        <div class="form-group">
            <label for="name">Nome:</label>
            <input type="text" id="name" name="name" class="form-control" placeholder="Despesa" required>
        </div>

        <div class="form-group">
            <div class="form-check">
                <input type="checkbox" id="is_installment" name="is_installment" class="form-check-input">
                <label for="is_installment" class="form-check-label">Parcelado</label>
            </div>
        </div>

        <div id="installment-fields" style="display: none;">
            <!-- Campos para despesas parceladas -->
            <div class="form-group">
                <label for="installment_value">Valor da Parcela:</label>
                <input type="text" id="installment_value" name="installment_value"
                       oninput="formatarMoeda('installment_value')" class="form-control" step="0.01">
            </div>
            <div class="form-group">
                <label for="installment_count">Número de Parcelas:</label>
                <input type="number" id="installment_count" name="installment_count" class="form-control" value="1">
            </div>
            <div class="form-group">
                <label>Valor Restante:</label>
                <span id="valor_restante"></span>
            </div>
            <div class="form-group">
                <label for="due_date">Inicio da parcela:</label>
                <input type="date" id="due_date" name="due_date" class="form-control">
            </div>
            <div class="form-group">
                <label>Informações das Parcelas:</label>
                <div id="parcelas-list">
                    <!-- Os três primeiros itens da lista de parcelas são exibidos aqui -->
                </div>
                <div id="show-all-installments" style="display: none;">
                    <!-- Os demais itens da lista de parcelas são exibidos aqui quando o usuário clica em "Ver todas as parcelas" -->
                </div>
                <span id="show-installments-span" class="link-span" style="display: none;">Ver todas as parcelas</span>
            </div>
        </div>

        <div class="form-group" id="value-field">
            <label for="currency">Moeda: <span style="color: red">(Não funciona ainda)</span></label>
            <select id="currency" name="category" class="form-control">
                <option value="" selected disabled>Selecione uma moeda</option>
                {% for category in user.categories %}
                <option value="{{ category.id }}">{{ category.name }}</option>
                {% endfor %}
            </select>
            <label for="value">Valor total:</label>
            <input type="text" id="value" name="value" oninput="formatarMoeda('value')" placeholder="Insira o valor"
                   class="form-control">
        </div>

        <div class="form-group" id="date-field">
            <label for="date">Data:</label>
            <input type="date" id="date" name="date" class="form-control">
        </div>

        <div class="form-group">
            <label for="category">Categoria:</label>
            <select id="category" name="category" class="form-control">
                <option value="" selected disabled>Selecione uma categoria</option>
                <option value="1">Alimentação</option>
                <option value="2">Transporte</option>
                <option value="3">Moradia</option>
                <option value="4">Lazer</option>
                <option value="5">Educação</option>
                {% for category in user.categories %}
                <option value="{{ category.id }}">{{ category.name }}</option>
                {% endfor %}
            </select>
        </div>

        <div class="form-group">
            <label for="comment">Observação:</label>
            <textarea id="comment" name="comment" class="form-control" maxlength="500"></textarea>
        </div>

        <button type="submit" class="btn btn-primary">Criar Despesa</button>
    </form>
</div>
{% endblock %}

{% block script %}
<script src="{{ url_for('static', filename='expense.js') }}"></script>
{% endblock %}

website/templates/home.html
{% extends "base.html" %}
{% block title %} Página Inicial {% endblock %}

{% block head %}
<style>
    .confirmation-dialog {
        display: none;
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background-color: rgba(0, 0, 0, 0.6);
        z-index: 9999;
    }

    .confirmation-dialog-content {
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        background-color: white;
        padding: 20px;
        border-radius: 8px;
        text-align: center;
    }

    .confirmation-dialog-buttons {
        margin-top: 20px;
    }

    .confirmation-dialog-buttons button {
        margin-right: 10px;
    }

</style>
{% endblock %}

{% block content %}
<div class="expenses">
    <h2>Despesas</h2>
    <h5>Valor total de despesas: R$ {{ '{:,.2f}'.format(total_value|float) }}</h5>
    <div id="confirmation-dialog" class="confirmation-dialog">
        <div class="confirmation-dialog-content">
            <p id="confirmation-message"></p>
            <div class="confirmation-dialog-buttons">
                <button id="confirm-button" class="btn btn-primary">OK</button>
                <button id="cancel-button" class="btn btn-primary">Cancel</button>
            </div>
        </div>
    </div>
    {% if user.expenses %}
    <ul class="list-group list-group-flush">
        {% for expense in user.expenses %}
        <li class="list-group-item">
            <strong>Nome:</strong> {{ expense.name }}<br>
            <strong>Valor da despesa:</strong> R$ {{ '{:,.2f}'.format(expense.value|float) }}<br>
            <strong>Data da despesa:</strong> {{ expense.date.split('-')[2] }}/{{ expense.date.split('-')[1] }}/{{
            expense.date.split('-')[0] }}<br>
            <strong>Categoria:</strong> {{ expense.default_cat }}<br>
            {% if expense.comment != ''%}
            <strong>Observação:</strong> {{ expense.comment }}<br>
            {% endif %}
            {% if expense.is_installment %}
            <strong>Parcelas:</strong>
            <ul>
                <li>
                    Valor: R$ {{ '%.2f'|format(expense.installment_value|float) }}<br>
                    Inicio: {{ expense.due_date.split('-')[2] }}/{{ expense.due_date.split('-')[1] }}/{{
                    expense.due_date.split('-')[0] }}<br>
                    Número de parcelas: {{ expense.installment_count }}<br>
                </li>
            </ul>
            {% endif %}
            <!--<a href="{{ url_for('views.edit_expense', expense_id=expense.id) }}">Editar</a>-->
            <a href="#" onclick="window.alert('Função indisponivel no momento (Ta com bug pra variar 😢)')">Editar</a>
            <a href="#"
               onclick="showConfirmationDialog('{{ url_for('views.delete_expense', expense_id=expense.id) }}', 'Você tem certeza de que deseja excluir a despesa {{ expense.name }}?');">
                Excluir
            </a>
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <p>Nenhuma despesa encontrada.</p>
    {% endif %}
</div>

{% endblock %}

{% block script %}

<script>
    function showConfirmationDialog(deleteUrl, message) {
        const confirmationDialog = document.getElementById('confirmation-dialog');
        const confirmationMessage = document.getElementById('confirmation-message');
        const confirmButton = document.getElementById('confirm-button');
        const cancelButton = document.getElementById('cancel-button');

        confirmationMessage.textContent = message;
        confirmationDialog.style.display = 'block';

        confirmButton.onclick = function () {
            window.location.href = deleteUrl;
        };

        cancelButton.onclick = function () {
            confirmationDialog.style.display = 'none';
        };
    }
</script>

{% endblock %}

website/templates/login.html
{% extends "base.html" %}
{% block head %}
{% endblock %}
{% block title %} Login {% endblock %}
{% block content %}
<form method="post">
    <h3 align="center">Login</h3>
    <div class="form-group">
        <label for="email">E-mail</label>
        <input type="email" class="form-control" id="email" name="email" placeholder="Digite seu email"
               required>

        <label for="password">Senha</label>
        <input type="password" class="form-control" id="password" name="password" placeholder="Digite sua senha"
               required maxlength="24" minlength="8"><br>

        <div align="center"><input type="submit" value="Login" class="btn btn-primary" disabled>&nbsp;<a href="/auth/sign-up" style="">Criar uma conta</a></div>
    </div>
</form>
<script src="{{ url_for('static', filename='login.js') }}"></script>
{% endblock %}

website/templates/sign-up.html
{% extends "base.html" %}
{% block title %} Registrar {% endblock %}
{% block content %}
<form id="registro-form" method="post">
    <h3 align="center">Registrar</h3>
    <div class="form-group">
        <label for="email">Digite seu e-mail</label>
        <input type="email" class="form-control" id="email" name="email" placeholder="Seu email" required>

        <label for="nome">Nome</label>
        <input type="text" class="form-control" id="nome" name="nome" placeholder="Seu nome" required minlength="1" maxlength="50">

        <label for="sobrenome">Sobrenome</label>
        <input type="text" class="form-control" id="sobrenome" name="sobrenome" placeholder="Seu sobrenome" required minlength="1" maxlength="50">

        <label for="password">Senha</label>
        <input type="password" class="form-control" id="password" name="password" placeholder="Digite sua senha"
               required maxlength="24" minlength="8">

        <label for="password2">Repita a senha</label>
        <input type="password" class="form-control" id="password2" name="password2" placeholder="Repita a sua senha"
               required maxlength="24" minlength="8">

        <span  id="erro-senha"  style="color: red;"></span><br>

    <div align="center"><input id="btn_registrar" type="submit" value="Registrar" class="btn btn-primary" disabled>&nbsp;<a href="/auth/login">Já tem uma conta?</a></div>
    </div>
</form>
{% endblock %}
{% block script %}
<script src="{{ url_for('static', filename='registro.js') }}"></script>
{% endblock %}